id: winters_blessing
name: "Winter's Blessing"
tags: [cooldown, buff]
cast: { gcd_s: 0.0, cast_time_s: 0.0 }
cost: { ember: 0 }
cooldown_s: 60
off_gcd: true
pipeline:
  - type: apply_buff
    name: WintersBlessing
    duration_s: 20        # 9s duration
    spirit_bonus: .2